### ISSUE TITLE
Bug with whitespaces in title

### ISSUE THREAD

**Issue by kernusr** [webmasterskaya/scheduled-weekly-milestones#6]
Cannot put space between date and title.

If i configured action as:
```yml
 - uses: webmasterskaya/scheduled-weekly-milestones@v2
        id: run
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Задачи до "
          days: Friday
          count: 2
          format: LL
          locale: 'ru-RU'
```

i have titles without whitespace:
![изображение](https://github.com/user-attachments/assets/1ccbfc4a-3d43-4160-9d6d-bd5bb9f390b1)
